# Input/output configuration
input_dir: /tigress/jdezoort/train_1
output_dir: /tigress/jdezoort/IN_samples_large/IN_LP_2_phi_reflect
n_files: 1000

# Graph building configuration
selection:
    pt_min: 2 # GeV
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-5, 5]
    phi_reflect: true